package Remesadora;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Allan Daniel Arnaut Muñoz - 100580133
 */
public final class reportes extends javax.swing.JFrame {

    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost:3306/remesadora";
    static final String USER = "root"; 
    static final String PASS = "Yosoyesemismo.1025";
    private Connection conn = null;
    
    /**
     * Creates new form reportes
     */
    
    public reportes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jreportes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        repG = new javax.swing.JButton();
        repE = new javax.swing.JButton();
        repR = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        filtrar = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        Jreportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Destinatario", "Fecha", "Moneda", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Jreportes);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reporte de Transacciones");

        repG.setBackground(new java.awt.Color(0, 51, 102));
        repG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        repG.setForeground(new java.awt.Color(255, 255, 255));
        repG.setText("General");
        repG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repGActionPerformed(evt);
            }
        });

        repE.setBackground(new java.awt.Color(0, 51, 102));
        repE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        repE.setForeground(new java.awt.Color(255, 255, 255));
        repE.setText("Envios");
        repE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repEActionPerformed(evt);
            }
        });

        repR.setBackground(new java.awt.Color(0, 51, 102));
        repR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        repR.setForeground(new java.awt.Color(255, 255, 255));
        repR.setText("Retiros");
        repR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repRActionPerformed(evt);
            }
        });

        volver.setBackground(new java.awt.Color(0, 51, 102));
        volver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filtro por Fecha");

        buscar.setBackground(new java.awt.Color(0, 51, 102));
        buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(repG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(repE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(repR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filtrar)
                            .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 98, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(repG, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(repE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(repR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repGActionPerformed
        // TODO add your handling code here:
        
        try{
            
            DefaultTableModel modelo = new DefaultTableModel();
            Jreportes.setModel(modelo);
            
            PreparedStatement ps;    
            ResultSet rs;
            Connection con = conectar();
            
            String query = "SELECT destinatario, fecha_envio, moneda, monto FROM envios";
            ps = con.prepareStatement (query);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("Destinatario");
            modelo.addColumn("Fecha");
            modelo.addColumn("Moneda");
            modelo.addColumn("Monto");
            
            while(rs.next()){
                
                Object[] filas = new Object[cantColumnas];
                
                for (int i = 0; i<cantColumnas; i++){
                
                    filas[i] = rs.getObject(i + 1);                    
                }                
                modelo.addRow(filas);
            }

            query = "SELECT receptor, fecha_retiro, moneda_retiro, monto FROM retiros";
            ps = con.prepareStatement (query);
            rs = ps.executeQuery();            

            while(rs.next()){
                Object[] filas2 = new Object[cantColumnas];
                
                for (int i = 0; i<cantColumnas; i++){
                
                    filas2[i] = rs.getObject(i + 1);                    
                }                
                modelo.addRow(filas2);
            }            
        }catch(SQLException e){
            System.err.println(e.toString());            
        }
    }//GEN-LAST:event_repGActionPerformed

    private void repEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repEActionPerformed
        // TODO add your handling code here:
        
            try{
            
            DefaultTableModel modelo = new DefaultTableModel();
            Jreportes.setModel(modelo);
            
            PreparedStatement ps;    
            ResultSet rs;
            Connection con = conectar();
            
            String query = "SELECT destinatario, fecha_envio, moneda, monto FROM envios";
            ps = con.prepareStatement (query);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("Destinatario");
            modelo.addColumn("Fecha");
            modelo.addColumn("Moneda");
            modelo.addColumn("Monto");
            
            while(rs.next()){
                
                Object[] filas = new Object[cantColumnas];
                
                for (int i = 0; i<cantColumnas; i++){
                
                    filas[i] = rs.getObject(i + 1);                    
                }                
                modelo.addRow(filas);
            }            
        }catch(SQLException e){
            System.err.println(e.toString());            
        }        
    }//GEN-LAST:event_repEActionPerformed

    private void repRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repRActionPerformed
        // TODO add your handling code here:
        
            try{
   
            DefaultTableModel modelo = new DefaultTableModel();
            Jreportes.setModel(modelo);
            
            PreparedStatement ps;    
            ResultSet rs;
            Connection con = conectar();
            
            String query = "SELECT receptor, fecha_retiro, moneda_retiro, monto FROM retiros";
            ps = con.prepareStatement (query);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("Destinatario");
            modelo.addColumn("Fecha");
            modelo.addColumn("Moneda");
            modelo.addColumn("Monto");
            
            while(rs.next()){
                Object[] filas = new Object[cantColumnas];
                
                for (int i = 0; i<cantColumnas; i++){
                
                    filas[i] = rs.getObject(i + 1);                    
                }                
                modelo.addRow(filas);
            }        
        }catch(SQLException e){
            System.err.println(e.toString());            
        }        
    }//GEN-LAST:event_repRActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        
        Home HomeFrame = new Home();
        HomeFrame.setVisible(true);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null);
        this.dispose();
     
    }//GEN-LAST:event_volverActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        
        String Filtrar1 = filtrar.getText();
        //String Filtrar2 = filtrar.getText();
        //String where_envio = "";
        //String where_retiro = "";
        
        if("".equals(Filtrar1)){
            JOptionPane.showMessageDialog(new JFrame(), "Es necesario colocar una fecha", "Error",
            JOptionPane.ERROR_MESSAGE);
        } else if(!"".equals(Filtrar1)){
            
            try{
            
                DefaultTableModel modelo = new DefaultTableModel();
                Jreportes.setModel(modelo);
            
                PreparedStatement ps;    
                ResultSet rs;
                Connection con = conectar();
            
                String query = "SELECT destinatario, fecha_envio, moneda, monto FROM envios WHERE fecha_envio = '" + Filtrar1 + "'";
                ps = con.prepareStatement (query);
                rs = ps.executeQuery();
            
                ResultSetMetaData rsMd = rs.getMetaData();
                int cantColumnas = rsMd.getColumnCount();
            
                modelo.addColumn("Destinatario");
                modelo.addColumn("Fecha");
                modelo.addColumn("Moneda");
                modelo.addColumn("Monto");
            
                while(rs.next()){
                    Object[] filas = new Object[cantColumnas];
                
                    for (int i = 0; i<cantColumnas; i++){
                
                        filas[i] = rs.getObject(i + 1);                    
                    }                
                    modelo.addRow(filas);
                }
             
                query = "SELECT receptor, fecha_retiro, moneda_retiro, monto FROM retiros WHERE fecha_retiro = '" + Filtrar1 + "'";
                ps = con.prepareStatement (query);
                rs = ps.executeQuery();            

                while(rs.next()){
                    Object[] filas2 = new Object[cantColumnas];
                
                    for (int i = 0; i<cantColumnas; i++){
                
                        filas2[i] = rs.getObject(i + 1);                    
                    }                
                    modelo.addRow(filas2);
                }
            
                filtrar.setText("");            
            }catch(SQLException e){
            System.err.println(e.toString());           
            }           
        }    
    }//GEN-LAST:event_buscarActionPerformed

    public Connection conectar() {

        try {
            
            Class.forName(JDBC_DRIVER);

            conn = DriverManager.getConnection(DB_URL, USER, PASS);
        } catch (SQLException se) {
            // Manejo de errores de JDBC
            se.printStackTrace();
        } catch (Exception e) {
            // Manejo de errores generales
            e.printStackTrace();
        } 
        return conn;
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jreportes;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField filtrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton repE;
    private javax.swing.JButton repG;
    private javax.swing.JButton repR;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
